//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acreator_front.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndexModel_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexModel_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("acreator_front.Resources.Pages.IndexModel_en", typeof(IndexModel_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string nav_home {
            get {
                return ResourceManager.GetString("nav-home", resourceCulture);
            }
        }
        
        internal static string nav_gallery {
            get {
                return ResourceManager.GetString("nav-gallery", resourceCulture);
            }
        }
        
        internal static string nav_contact {
            get {
                return ResourceManager.GetString("nav-contact", resourceCulture);
            }
        }
        
        internal static string nav_about {
            get {
                return ResourceManager.GetString("nav-about", resourceCulture);
            }
        }
        
        internal static string nav_products {
            get {
                return ResourceManager.GetString("nav-products", resourceCulture);
            }
        }
        
        internal static string nav_selectLang {
            get {
                return ResourceManager.GetString("nav-selectLang", resourceCulture);
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        internal static string sub_quest {
            get {
                return ResourceManager.GetString("sub-quest", resourceCulture);
            }
        }
        
        internal static string products_link {
            get {
                return ResourceManager.GetString("products-link", resourceCulture);
            }
        }
    }
}
