//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acreator_front.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivacyModel_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyModel_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("acreator_front.Resources.Pages.PrivacyModel_en", typeof(PrivacyModel_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string who {
            get {
                return ResourceManager.GetString("who", resourceCulture);
            }
        }
        
        internal static string who_ans {
            get {
                return ResourceManager.GetString("who-ans", resourceCulture);
            }
        }
        
        internal static string what {
            get {
                return ResourceManager.GetString("what", resourceCulture);
            }
        }
        
        internal static string what_ans {
            get {
                return ResourceManager.GetString("what-ans", resourceCulture);
            }
        }
        
        internal static string why {
            get {
                return ResourceManager.GetString("why", resourceCulture);
            }
        }
        
        internal static string why_ans {
            get {
                return ResourceManager.GetString("why-ans", resourceCulture);
            }
        }
    }
}
