//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acreator_front.Resources.Pages.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_az {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_az() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("acreator_front.Resources.Pages.Shared._Layout_az", typeof(_Layout_az).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string nav_home {
            get {
                return ResourceManager.GetString("nav-home", resourceCulture);
            }
        }
        
        internal static string nav_gallery {
            get {
                return ResourceManager.GetString("nav-gallery", resourceCulture);
            }
        }
        
        internal static string nav_about {
            get {
                return ResourceManager.GetString("nav-about", resourceCulture);
            }
        }
        
        internal static string nav_products {
            get {
                return ResourceManager.GetString("nav-products", resourceCulture);
            }
        }
        
        internal static string nav_contact {
            get {
                return ResourceManager.GetString("nav-contact", resourceCulture);
            }
        }
        
        internal static string nav_selectLang {
            get {
                return ResourceManager.GetString("nav-selectLang", resourceCulture);
            }
        }
        
        internal static string footer_info {
            get {
                return ResourceManager.GetString("footer-info", resourceCulture);
            }
        }
        
        internal static string footer_hours {
            get {
                return ResourceManager.GetString("footer-hours", resourceCulture);
            }
        }
        
        internal static string sat {
            get {
                return ResourceManager.GetString("sat", resourceCulture);
            }
        }
        
        internal static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
    }
}
